services:
  app:
    build: .
    container_name: app
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:docker:dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_API_VERSION=${APP_API_VERSION}
      - DEFAULT_PAGE=${DEFAULT_PAGE}
      - DEFAULT_LIMIT=${DEFAULT_LIMIT}
      - DB_HOST=test-db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DIALECT=${DB_DIALECT}
      - DB_NAME_DEVELOPMENT=${DB_NAME_DEVELOPMENT}
      - DB_NAME_PRODUCTION=${DB_NAME_PRODUCTION}
      - DB_NAME_TEST=${DB_NAME_TEST}
      - DB_MIGRATION_TABLE=${DB_MIGRATION_TABLE}
      - JWT_KEY=${JWT_KEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - BEARER=${BEARER}
    depends_on:
      - test-db

  test-db:
    image: postgres:16.1
    container_name: test-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME_DEVELOPMENT}
    volumes:
      - ./postgres:/var/lib/postgres/data
    ports:
      - ${DB_PORT}:${DB_PORT}
