services:
  database:
    image: postgres:16.1
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME_DEVELOPMENT}
    volumes:
      - ./postgres:/var/lib/postgres/data
    ports:
      - ${DB_PORT}:${DB_PORT}
